### ISSUE TITLE
[FEATURE] 레이아웃 추가

### ISSUE THREAD

**Issue by marshot9420** [marshot9420/marswork#1]
### 📄 Describe

레이아웃 추가

### ✅ Tasks

- [ ] `SlideMenuButton` 컴포넌트 추가
- [ ] `SearchBar` 컴포넌트 추가
- [ ] `InfoDisplay` 컴포넌트 추가
- [ ] `Header` 컴포넌트 추가
- [ ] `GridSection` 컴포넌트 추가
- [ ] `Layout` 구현

### 🙋🏻 More

헤더와 그리드 섹션에는 데스크탑, 랩탑, 태블릿 PC, 모바일에 따라 반응형으로 동작
