### ISSUE TITLE
[FEATURE] 레이아웃 구현

### ISSUE THREAD

**Issue by marshot9420** [marshot9420/marswork#1]
### 📄 Describe

레이아웃 요소를 배치하고 영역을 설정합니다.

### ✅ Tasks

- [ ] `header` 컴포넌트 구현
- [ ] `sidebar` 컴포넌트 구현
- [ ] `main` 컴포넌트 그리드 구현
- [ ] `footer` 컴포넌트 구현

### 🙋🏻 More

반응형 그리드
